#!/bin/bash

#set -x
echo "Début de l'installation"
CIBLE="/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions"

# On vérifie la présence du dossier $CIBLE qui signifie qu'Inkscape est bien installé
if [ -d $CIBLE ]; then
    # Inkscape Version
    inkscapeVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" /Applications/Inkscape.app/Contents/Info.plist | cut -c1-4)

    if [[ $inkscapeVersion == "0.91" ]]; then
        echo "Inkscape 0.91 a été détecté sur votre machine, nous procédons à l'installation du plugin Xia..."
        echo "Copie des fichiers en cours..."
        cp -r ./files/* "$CIBLE"
        echo "Copie des fichiers terminée !"

	sleep 2

	if [ -d "/Applications/xia.app" ]; then
		echo "Tentative de récupération des thèmes de l'ancienne application..."	
		for theme in $(ls /Applications/xia.app/Contents/Resources/share/themes/); do
			if [[ $theme != "accordionBlack" && $theme != "accordionCloud" && $theme != "audioBrown" && $theme != "buttonBlue" && $theme != "game1clic" && $theme != "gameDragAndDrop" && $theme != "popBlue" && $theme != "popYellow" ]]; then
				sudo -u root cp -r "/Applications/xia.app/Contents/Resources/share/themes/$theme" $CIBLE/share/themes/
				echo "$theme copié."
			fi
		done
		
		echo "Suppression de l'ancienne application..."
		sudo -u root rm -rf "/Applications/xia.app"
	fi
	
	echo "Suppression des anciennes extensions Xia..."
	for user in $(ls /Users/); do
		if [[ $user != "Shared" ]]; then
			if [ -d "/Users/$user/.config/inkscape/extensions/xiaconverter" ]; then
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/PIL"
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/xia.cnf"
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/xia.inx"
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/xia.py"
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/xiaconverter"
				sudo -u root rm -rf "/Users/$user/.config/inkscape/extensions/share"
			fi
		fi
	done

        echo "Fin de l'installation."
    else
        # Pour le moment, on alerte que seule la version 0.91.alphabetagammatrucchose permet d'utiliser l'extension Xia
        echo "Votre version d'Inkscape n'est pas à jour."
        echo "Vous trouverez la dernière version ici :"
        echo "https://inkscape.org/fr/telecharger/"
        echo "Installation annulée."
    fi
else
    echo "Inkscape est nécessaire pour pouvoir utiliser Xia."
    echo "Vous pouvez le télécharger ici :"
    echo "https://inkscape.org/fr/telecharger/"
    echo "Installation annulée."
fi
